### ISSUE TITLE
String Serialization compatibility with old WindowsAzure.ServiceBus assembly

### ISSUE THREAD

**Issue by bledbet** [Azure/azure-service-bus#247] opened 2018-10-31 13:45 UTC
# Description
We have hundreds of services running in production using the old WindowsAzure.ServiceBus assembly, and it may have been a mistake, but but when sending a message we have been using the BrokeredMessage constructor that just lets you pass in a string, and when receiving the message we have been using the  `BrokeredMessage.GetBody<string>() ` method.

I am working to convert our services to the newer Microsoft.Azure.ServiceBus assembly, and I need to be able to use it in a way that is compatible with existing services.  On the receiving end, the new servicebus assembly still supports `Message.GetBody<string>()` method, which appears compatible with messages that were sent by the old assembly as described.  However, the Message class does not have a constructor that lets you just pass in the string, so I am currently using `new Message(Encoding.UTF8.GetBytes(body))` constructor.  Unfortunately, it seems that this does not produce some serializtion headers or something that are required for the receiving end to deserialize the message with the `GetBody<string>()` method.

A service using the old assembly gets:

System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type System.String. The input source is not correctly formatted. ---> System.Xml.XmlException: The input source is not correctly formatted.

(A service with the new version of the assembly gets the same exception when using `GetBody<string>()` 
but my concern at the moment is to find a strategy that lets me roll out the new assembly without having to install hundreds of services simultaneously)

So what I need to know is how I can send messages from the new Microsoft.Azure.ServiceBus assembly in a way such that the old assembly, using `GetBody<string>()` can read them.

## Actual Behavior
1. A new/updated service using Microsoft.Azure.ServiceBus assembly sends a message using the only constructor available:  `new Message(Encoding.UTF8.GetBytes(this.body))`

2. An old service using WindowsAzure.ServiceBus assembly throws SerializationException when a message is received and the body is accessed using `BrokeredMessage.GetBody<string>()`

## Expected Behavior
1. A solution using the new assembly that emulates the way the old assembly encoded the message when using `new BrokeredMessage(string)`

2. An old service using WindowsAzure.ServiceBus assembly can successfully access `BrokeredMessage.GetBody<string>() `

**Comment by SeanFeldman** [comment] 2018-10-31 17:12
Looking a the expected behaviour, I'd say the following:

1. Have a look at https://github.com/Azure/azure-service-bus-dotnet/issues/239 for additional context and what ASB team thinks should be happening since the old client is not going to be worked on.
1. [Transfer this issue](https://help.github.com/articles/transferring-an-issue-to-another-repository/) to the new client repo

**Comment by bledbet** [comment] 2018-10-31 18:01
Thanks Sean - I think I can make that work.

**Closed** 2019-03-04 06:57 UTC
