### ISSUE TITLE
Implement support for WebSocket binding in com.azure.spring:spring-cloud-azure-starter-servicebus-jms Spring Boot Java library

### ISSUE THREAD

**Issue by andrianov17** [Azure/azure-service-bus#725] opened 2024-12-13 21:52 UTC
We need to switch from using 5671 AMQP port to 443 using WebSocket binding offered by Azure Service Bus.

Service Bus connection string supports TransportType=AmqpWebSockets parameter, but unfortunately, it has no impact on underlying QPID JMS connection factory initialization as of latest com.azure.spring:spring-cloud-azure-starter-servicebus-jms:5.18.0 Spring Boot starter library.

Could you please implement AMQP over WebSocket support?

**Comment by EldertGrootenboer** [comment] 2024-12-20 17:01
Duplicate of https://github.com/Azure/azure-servicebus-jms/issues/26, closing this issue in favor of the other one, as this is JMS specific. Please upvote on the other issue.

**Closed by EldertGrootenboer** 2024-12-20 17:01 UTC
Labels: duplicate
