### ISSUE TITLE
Queue assigns wrong Sequence number when resubmitted from a partitioned queue

### ISSUE THREAD

**Issue by DeepakMohanSingh** [Azure/azure-service-bus#465] opened 2022-02-25 15:28 UTC
# Description

## Actual Behavior
I face an issue when resubmitting a message from a partitioned queue to a conventional queue using dot net latest SDK. As partitioned queue assigns a sequence number that is relative to the partition (the topmost 16 bits reflect the partition identifier), when I resubmit a message from this partitioned queue to a normal queue (which has just 3-4 messages with sequence number like 1,2,3,4), the new message that lands on the queue has a strange sequence number! (The sequence number assignment looks like how it looks in the partitioned queue - 16 digits for example). 

## Expected Behavior
Shouldn't this sequence number be something like "5" in my conventional queue (I mean, relative to the existing messages in my queue)?

Repro steps:

```
ServiceBusReceivedMessage _message = await receiverClient.PeekMessageAsync(); // receiverClient connects with partitioned queue
ServiceBusMessage message = new ServiceBusMessage(_message);
await senderClient.SendMessageAsync(message); // senderClient connects with conventional queue
```

Other problems due to this behaviour:
- I am not able to purge the messages with such sequence number. I tried with my code, and with Service Bus Explorer too.

**Comment by SeanFeldman** [comment] 2022-03-24 20:31
Do you see this with a single namespace or can reproduce with other namespaces?

**Comment by EldertGrootenboer** [comment] 2022-07-21 17:07
We have added this to our backlog to investigate the behavior you are seeing. Will come back to this issue when we have more information.

**Comment by EldertGrootenboer** [comment] 2023-10-13 19:08
Thank you for your feedback on this item. We are currently doing active development on this feature, and expect to have more to share around its release in the next couple of months.

**Comment by EldertGrootenboer** [comment] 2023-11-08 02:20
We have finished our investigation, and found that the specific method you are using to receive the message and then forward (or resubmit) it to another queue is the only scenario in which this issue can be reproduced. When attempting to forward the message from one queue to another in any other manner, the messages in the non-partitioned queue are numbered correctly.

The cause lies in how you are trying to convert a ServiceBusReceivedMessage directly into a ServiceBusMessage. Instead, the recommended approach to forward a message from one queue to another using the SDK is as follows.

```csharp
    // Receive for q1_p - partitioned queue
    ServiceBusReceiver receiver = client.CreateReceiver("q1_p");
    ServiceBusReceivedMessage receivedMessage = await receiver.ReceiveMessageAsync();

    // Send to q1 - non-partitioned queue
    ServiceBusMessage receivedMessageTwo = new ServiceBusMessage(receivedMessage.Body);
    receivedMessageTwo.MessageId = receivedMessage.MessageId; // if the customer wishes to duplicate the message id​
    await senderOne.SendMessageAsync(receivedMessageTwo);
```

A ServiceBusReceivedMessage cannot be directly converted to a ServiceBusMessage because ServiceBusReceivedMessage contains additional read-only properties that are set by the service when the message is received.

However, if you wish to forward a received message to another queue or topic, you can create a new ServiceBusMessage using the body of the ServiceBusReceivedMessage. If necessary, you can also copy the MessageId. This is the recommended approach for forwarding messages.

**Comment by EldertGrootenboer** [comment] 2023-11-09 22:56
We have identified this as a client side issue, hence closing this issue. The progress for the fix can be tracked at https://github.com/Azure/azure-sdk-for-net/issues/39886.

**Closed by EldertGrootenboer** 2023-11-09 22:56 UTC
Labels: backlog, investigate
