### ISSUE TITLE
DeferAsync() moves the message to the DLQ if Max Delivery Count is 1

### ISSUE THREAD

**Issue by martyt** [Azure/azure-service-bus#375] opened 2020-10-02 15:54 UTC
# Description

If the Service Bus Queue is configured with "Max Delivery Count" = 1, calls to `DeferAsync()` result in the message being moved to the Dead Letter Queue with an error message indicating max delivery count was exceeded. 

Changing Max Delivery Count to a value > 1 results in a properly deferred message. 

## Actual Behavior
1. When Max Delivery Count = 1, `DeferAsync()` moves the message to the Dead Letter Queue.

## Expected Behavior
1. `DeferAsync()` should defer the message, regardless of the Max Delivery Count setting.

**Comment by qsdfplkj** [comment] 2021-03-19 20:37
The delivery count is incremented each time it is processed regardless of being deferred or not. When it reaches the maximum delivery count it goes to the dead letter queue. I'm not sure why I would expect the one over the other.

**Comment by SeanFeldman** [comment] 2021-03-20 00:05
Perhaps I'm missing something here but this sounds like the right behavior.
When the `MaxDeliveryCount` is configured as 1, it literally says "do not attempt delivery more than once. If you need to defer the message, account for that by setting `MaxDeliveryCount` to a value larger than 1.

**Comment by triynko** [comment] 2021-03-20 01:39
Deferring the message means you're still in the middle of processing it. In other words you're still actively operating on the original delivery attempt. In fact, the message isn't even eligible for delivery when deferred because only the thing that deferred it and has its sequence number can lock it to continue processing. Only an  Abandon call ends the original delivery attempt and processing attempt.

It seems to me like trashing the message while you're still trying to process it (deferred) is a bug. Deferring a message is explicitly for processing a message for an extended time.

**Comment by SOHODeveloper** [comment] 2021-05-12 13:31
I believe that we could make a case that deferring should not update the delivery count.  However, I suspect the delivery count is incremented as the message is given to the client instead of during its disposition (settlement).

Let us consider the following use case.
Message of significant importance, and under normal circumstances has a delivery of 2 so that that the message processing could fail once and succeed on the second attempt without going to the DLQ.  Enter the fact that we need to be able to defer the message.  Deferring is not a FAILURE as such and should have different semantics.  By preventing the deferral from incrementing delivery, we could explicitly receive and defer the message many times (application would have to track the deferral count to prevent infinite attempts) and then still have the original fail once and retry semantics that were in place before the defer processing was added.

As it stands with deferring increasing the delivery count, the only reasonable choice is to max out (or use large reason number) for max delivery count and then the application would have to manage moving message to DLQ after second failure, but allow defers to continue as required.

The key here is a defer is not a failure and needs to be handled differently.

**Comment by qsdfplkj** [comment] 2021-05-12 18:51
A message is on the queue while delivery count < max count. If count == max then it moves to the DLQ.  If max count is set to one you cannot really defer it. If you set it to 2 you can defer it. And manually receive it using … It then also adds one to delivery count. So you cannot receive it more than twice in total.

**Comment by EldertGrootenboer** [comment] 2022-08-05 21:22
As mentioned by @SeanFeldman this behavior is by design. Deferring means the message was already delivered, and as such, the delivery count will be increased.

**Closed by EldertGrootenboer** 2022-08-05 21:22 UTC
