### ISSUE TITLE
Incorrect exception message from the broker

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#103] opened 2017-10-17 05:43 UTC
For the following code

```c#
var queueClient = new QueueClient(connectionString, queueName, ReceiveMode.PeekLock);
var message = new Message(Encoding.UTF8.GetBytes("Message"));
await queueClient.SendAsync(message);
```

where destination queue has
- `RequireDuplicateDetection = true`
- `EnablePartitioning = true`

Exception thrown is:

```
Batching brokered messages with distinct SessionId, PartitionKey, or MessageId  
is not supported for an entity with partitioning and duplicate detection enabled.
```

seems to be incorrect. 

1. It should indicate that "_Batching brokered messages **without** distinct SessionId, PartitionKey, or MessageId  is not supported for an entity with partitioning and duplicate detection enabled._".
1. The code doesn't send a batch, yet the error message points out a batching operation was attempted.

**Comment by ChristianWolf42** [comment] 2017-11-14 22:55
@SeanFeldman we will investigate that a bit more and get back

**Comment by grahambunce** [comment] 2018-02-25 13:20
Any update on this, it's really annoying and appears to be serious a bug. I'm sending two messages at once to the same queue, in each case the message id is set to be a unique value, and I'm getting this error "Batching brokered messages with distinct SessionId, PartitionKey, or MessageId  is not supported for an entity with partitioning and duplicate detection enabled"

My Queue properties are:

"properties": {
    "path": "notification",
    "lockDuration": "00:01:00",
    "maxSizeInMegabytes": 16384,
    "requiresDuplicateDetection": true,
    "requiresSession": false,
    "defaultMessageTimeToLive": "14.00:00:00",
    "deadLetteringOnMessageExpiration": true,
    "duplicateDetectionHistoryTimeWindow": "00:01:00",
    "maxDeliveryCount": 10,
    "enableBatchedOperations": false,
    "sizeInBytes": 0,
    "messageCount": 0,
    "isAnonymousAccessible": false,
    "status": "Active",
    "createdAt": "2018-02-22T22:46:41.09Z",
    "updatedAt": "2018-02-25T12:55:24.4058832Z",
    "accessedAt": "2018-02-25T13:18:09.2026694Z",
    "supportOrdering": false,
    "countDetails": {
      "activeMessageCount": 0,
      "deadLetterMessageCount": 0,
      "scheduledMessageCount": 0,
      "transferMessageCount": 0,
      "transferDeadLetterMessageCount": 0
    },
    "autoDeleteOnIdle": "10675199.02:48:05.4775807",
    "enablePartitioning": true,
    "entityAvailabilityStatus": "Available",
    "enableExpress": false
  }

Why can't I send two messages at once??

I'm using the .net core Microsoft.Azure.ServiceBus package 2.0.0

**Comment by SeanFeldman** [comment] 2018-02-25 15:36
> I'm using the .net core Microsoft.Azure.ServiceBus package 2.0.0

The client you're using is a new one, but it's a broker side exception as @binzywu indicated https://github.com/Azure/azure-service-bus/issues/103#event-1303374407. Once it's fixed on the server side, it will be addressed for both clients.

**Comment by grahambunce** [comment] 2018-02-25 16:57
Thanks @SeanFeldman. Regardless it seems a serious bug not to be fixed yet (we have to adjust our code to suit, and make it less efficient to boot). Also, I'd like to understand why this is deemed a server side issue - I'm pretty sure (need to check) that my .net 4.6.1 code using the original .NET client doesn't have this problem

**Comment by nemakam** [comment] 2018-03-30 01:52
@grahambunce @SeanFeldman 
Just clearing expectations here:
When you are sending a batch of messages to a partitionedqueue, the entire batch should ideally land in the same backend for the batch operation to succeed (since batch send is a transactional send by default).
So it is not right to send a batch of messages with different MessageId/PartitionKey. 

@grahambunce 
You will need to make sure in a single batch, all the messages have the same messageId/partitionKey. i.e., the error you are seeing is by design.

@SeanFeldman 
Now if the message is going to a duplicate-detection queue, then it is required that it is routed to the right partition. Hence it is mandatory to have either PartitionKey/MessageId mentioned in the message. So to fix the error, just set the messageId or partitionKey to some value. 
FYI, If partitionKey is null, then messageId is used for partitioning logic only in case of duplicate-detection queue. 

I'm going to keep the issue open though so that we can address the exception message.

**Comment by grahambunce** [comment] 2018-03-30 12:40
@nemakam How can they have the same message id? Doesn't this uniquely identify the message? So that simply doesn't make sense, and it also prevents duplicate detection working.

Can I actually send multiple messages with different message ids but the same partition key? Do I need to explicitly set a partition key somehow? That doesn't make sense either as isn't partitioning an internal feature of the the service bus?

**Comment by SeanFeldman** [comment] 2018-03-30 17:14
> I'm going to keep the issue open though so that we can address the exception message.

👍 that was my first part of this issue 🙂 

When a queue is partitioned, absolutely correct that PartitionKey/MessageId/SessionId should be set.
What I was pointing out is that the message was referring to a _batch_.

**Comment by grahambunce** [comment] 2018-03-30 17:33
@nemakam The whole point of partitioning is so that if one partition is down, the infrastructure can seamlessly choose another partition. I don't care what partition my messages are sent to, just let me send several at once as they are transactionally consistent. What happens if I chose a random partition key (AFAIK there is no correlation between a value I choose and what physical partition is used) and the partition that gets assigned to happens to be down. Will the infrastructure pick this up and resend to a different partition for me?

@SeanFeldman Sorry for hijacking the thread :-o

**Comment by nemakam** [comment] 2018-03-30 18:24
@grahambunce 
> The whole point of partitioning is so that if one partition is down, the infrastructure can seamlessly choose another partition.

Correct.

> I don't care what partition my messages are sent to, just let me send several at once as they are transactionally consistent.

The single most important point is that transaction **cannot** span across partitions. So if you have multiple operations in a transaction, then they all have to go to the same partition. So the user is expected to use `partitionKey` to decide which partition it should go to. 
If you have specified a partitionKey, then there is no reason for our service to override your command. i.e., if partitionKey is set, then it will either land in that partition, or the request will fail. 

> AFAIK there is no correlation between a value I choose and what physical partition is used

We just hash the partitionKey to decide which partition the message should go to. So every message stamped with the same partitionKey WILL end up in the same partition. 

> I don't care what partition my messages are sent to, just let me send several at once as they are transactionally consistent

Another FYI, a `sendBatch` command is transactional in nature. i.e., even if you don't add your own transaction, but use `sendBatch` to send messages, either all of them will succeed or all of them will fail. So now you can decide to not use `partitionKey` if you are not particular about the partition it lands in.

I hope all your questions are answered

**Comment by nemakam** [comment] 2018-03-30 18:27
@SeanFeldman 
I'm keeping this issue open to address the _batch_ word, but not the _with/without_ conflict. IMO, _with_ is correct. If you have a batch of messages _with_ different `partitionKey`, then it indeed is an invalid operation.

**Comment by erik-neumann** [comment] 2018-05-16 10:03
While trying to send a batch of messages I got the same error message: `Batching brokered messages with distinct SessionId, PartitionKey, or MessageId  is not supported for an entity with partitioning and duplicate detection enabled`

I was using unique messageIds but did not explicitly set a partitionKey. I was confused why this is not working. Once I have set a unique partitionKey for all messages of the batch everything was fine.

To me the error message is misleading. I don't understand why it is complaining about sending distinct messageIds in a batch.

@nemakam I agree with sending messages having different partitionKey but not with messageId. IMO this is meant to be a unique Id and I should still be able to batch those messages (using same partitionKey).

According to MS docs the MessageId:

> Gets or sets the identifier of the message. This is a user-defined value that Service Bus can use to identify duplicate messages, if enabled.

**Comment by grahambunce** [comment] 2018-06-30 10:01
@nemakam I can also confirm that different message ids with the same partition key works fine. Therefore I agree that the error message is incorrect and, worse, it sends developers down the wrong rabbit hole (as it did with me), thereby changing their designs in completely the wrong way. This message

> Batching brokered messages with distinct SessionId, PartitionKey, or MessageId  is not supported for an entity with partitioning and duplicate detection enabled

Should IMO say something like

> Batching brokered messages with a different PartitionKey is not supported for an entity with partitioning enabled. If a PartitionKey is not set for a batch then set this to an explicit user-defined value

Then, it's pointing the correct problem (a PK needs to be set for a batch if that entity is enabled for partitioning) and that the user can fix it by setting their own value.

Message Id (and I presume Session Id) appear to be irrelevant to the problem itself.

**Comment by nemakam** [comment] 2018-07-02 22:56
> Message Id (and I presume Session Id) appear to be irrelevant to the problem itself.

@grahambunce When `partitionKey` is not set, `MessageID` is the key which decides the partitioning. But this happens only in the case when duplicate detection is enabled.

**Comment by nemakam** [comment] 2018-07-03 01:53
This has been fixed and will be released in the next release cycle.

**Closed by nemakam** 2018-07-03 01:53 UTC
Labels: bug, service side
