### ISSUE TITLE
How to set autoforward with ARM and the newer SDKs

### ISSUE THREAD

**Issue by adrianrbezzina** [Azure/azure-service-bus#107] opened 2017-10-26 01:39 UTC
We have come to a point where we are trying to now provision subscriptions to Service Bus Topics, which has been successful except being able to supply an AutoForward path (https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-auto-forwarding)

We seem to be unable to configure this at all via ARM or the newer management SDKs. It only seems possible with the older SDK.

## Actual Behavior
Can't set the ForwardTo property anywhere in either ARM or new (Node) SDKs

## Expected Behavior
Able to set the ForwardTo property in ARM and new SDKs

**Comment by SeanFeldman** [comment] 2017-10-26 05:20
Duplicate of #88

**Closed** 2017-10-26 05:22 UTC
Labels: duplicate
