### ISSUE TITLE
Incoming and outgoing messages count do not match

### ISSUE THREAD

**Issue by erickbp** [Azure/azure-service-bus#316] opened 2019-10-09 18:24 UTC
# Description
Queue has session enabled with 5 min lock duration for easy test. I'm reading messages with ISessionClient.AcceptMessageSessionAsync

I'm completing messages when they arrive (no processing delay)

No message lock is lost. My code receives the exact number of messages it sent (no message duplication received)

## Actual Behavior
1. When I look at the metrics it always shows more outgoing messages than income messages

## Expected Behavior
1. Incoming and outgoing messages should match

Is this how Service Bus works by design? maybe to accomplish the session work? or is the client library actually receiving duplicates and not sending them to my code? or is it just bad metrics on the azure portal?
Thanks
![image](https://user-images.githubusercontent.com/10678433/66508821-da057080-ea9f-11e9-9068-f590e1397eaa.png)
![image](https://user-images.githubusercontent.com/10678433/66508831-e093e800-ea9f-11e9-992b-a3bca80ce522.png)

**Comment by valmol** [comment] 2020-03-04 11:10
I also noticed the same behaviour.

**Comment by AlexeyRaga** [comment] 2020-06-30 23:36
I see this graph and I don't know how to interpret that. How the number of outgoing messages can be 4 times higher than the number of incoming messages?

![image](https://user-images.githubusercontent.com/1394391/86187082-52f0af00-bb7e-11ea-87ba-5479834ec20c.png)

Anyone has a suggesiton?

**Comment by SeanFeldman** [comment] 2020-07-02 04:25
One scenario I can think of is that you send messages in batches but receive either in smaller batches or one-by-one.

**Comment by JelmerOffenberg** [comment] 2020-07-02 13:24
I'm also seeing this behaviour and I'm curious to know what caused it. I have one topic with two subscribers and I sent a single message resulting in this chart.

![afbeelding](https://user-images.githubusercontent.com/10910757/86364202-25882c00-bc78-11ea-8139-94fdabe2c304.png)

**Comment by georgbergholz** [comment] 2020-07-24 06:34
I have the same behaviour and think it depends on the ReceiveMode.
PeekLock needs a complete request and ReceiveAndDelete delete the message by reading.

**Comment by RobertPinson** [comment] 2020-10-08 10:27
> I'm also seeing this behaviour and I'm curious to know what caused it. I have one topic with one subscriber and I sent a single message resulting in this chart.
> 
> ![afbeelding](https://user-images.githubusercontent.com/10910757/86364202-25882c00-bc78-11ea-8139-94fdabe2c304.png)

Hi @JelmerOffenberg Did you ever get an answer to this question? I am seeing the same in our SB queue more outgoing messages then incoming.

**Comment by rtwaddell** [comment] 2020-10-15 13:50
We are seeing the same behavior, has anyone found an answer to this?

**Comment by jimzcoi** [comment] 2021-02-22 12:10
Any progress with this strange behavior?  Is there a viable explanation of this variance of values?

**Comment by DavidKlempfner** [comment] 2021-05-19 06:52
I've got the same problem.
It's been almost 2 years since this was reported.
Can we get an answer please?
![image](https://user-images.githubusercontent.com/13111539/118768551-7e79a680-b8c2-11eb-883c-2f866804fb3c.png)

**Comment by aleprice** [comment] 2021-06-09 18:44
Same issue
![image](https://user-images.githubusercontent.com/26556978/121410946-7fd64600-c939-11eb-959a-7baa13fa15f8.png)

**Comment by MounicaChette** [comment] 2021-08-12 06:55
Team, Is there is resolution or fix for this issue. I am also facing mismatch in sum of Incoming Messages and Outgoing messages. The messages are being pushed to topic one by one, where as, there is a webjob sceduled to read messages from topic in bulk mode.  However, this behavior is strange. If i stop reading the messages, push all the messages, and then start reading the messages, then count of Incoming and Outgoing messages match.

![image](https://user-images.githubusercontent.com/16791909/129151432-b7a2ca28-1b43-4173-a4a0-a4d478a5c0be.png)

**Comment by JelmerOffenberg** [comment] 2021-11-24 14:48
> > I'm also seeing this behaviour and I'm curious to know what caused it. I have one topic with one subscriber and I sent a single message resulting in this chart.
> > ![afbeelding](https://user-images.githubusercontent.com/10910757/86364202-25882c00-bc78-11ea-8139-94fdabe2c304.png)
> 
> Hi @JelmerOffenberg Did you ever get an answer to this question? I am seeing the same in our SB queue more outgoing messages then incoming.

@RobertPinson unfortunately this problem was never resolved for us! We contacted Microsoft support but we received no satisfying answer. Seems like another one of those unexplainable features of Azure services.

**Comment by EldertGrootenboer** [comment] 2022-08-05 21:13
Because these metrics are aggregated in time intervals these can be skewed, for example due to slightly different clocks and retry mechanisms, especially when using a Sum aggregation. We recommend using the Average metric instead. Moreover, this is expected behavior when using topics, as each message in a topic will be replicated to one or more subscriptions. 

If you run into a specific instance where you see this kind of behavior which can not be explained by the above, please open a new issue, with reproduction steps.

**Closed by EldertGrootenboer** 2022-08-05 21:13 UTC
